apiVersion: v1
kind: Namespace
metadata:
  name: kubeevalhub-agent

---
apiVersion: v1
kind: Secret
metadata:
  name: kubeevalhub-agent-secret
  namespace: kubeevalhub-agent
type: Opaque
stringData:
  AGENT_TOKEN: "df68dd729cd943dae2ad49afc1a19976f93a57d5aa4a5416b2c6d27f76c0c772"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeevalhub-agent
  namespace: kubeevalhub-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeevalhub-agent
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeevalhub-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeevalhub-agent
subjects:
  - kind: ServiceAccount
    name: kubeevalhub-agent
    namespace: kubeevalhub-agent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeevalhub-agent
  namespace: kubeevalhub-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeevalhub-agent
  template:
    metadata:
      labels:
        app: kubeevalhub-agent
    spec:
      serviceAccountName: kubeevalhub-agent
      containers:
        - name: agent
          image: docker.io/lewaldenko/kubeevalhubagent:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_URL
              value: "http://host.minikube.internal:5000"
            - name: AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kubeevalhub-agent-secret
                  key: AGENT_TOKEN
            - name: SCRAPE_INTERVAL
              value: "30s"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
